# Generated by Django 5.1.3 on 2024-12-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_eleve_classe_delete_infrastructure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=255, unique=True)),
                ('classe', models.CharField(max_length=255, unique=True)),
                ('matiere', models.CharField(max_length=255)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
